---
data:
  train:
    data_roots:
      - /home/junsong_fan/diskf/data/cityscapes/leftImg8bit/train
      - /home/junsong_fan/diskf/data/cityscapes/gtFine_trainIds/train
    data_type: [Image, Label2D]
    image_size: [513, 1025]
    rand_short: [513, 1537]
    rand_crop: true
    rand_mirror: true
    image_suffix: [".png", "_trainIds.png"]

  test:
    data_roots:
      - /home/junsong_fan/diskf/data/cityscapes/leftImg8bit/val
      - /home/junsong_fan/diskf/data/cityscapes/gtFine/val
    data_type: [Image, Image]
    image_size: [1024, 2048]
    image_suffix: [".png", "_color.png"]

model:
  arch: vgg16_largefov
  pretrained: ./pretrained/vgg16_20M.pth
  attrs: 
    num_classes: 19
    dilation: 12
    mode: seg
 
schedule:
  lr: 1.e-3
  momentum: 0.9
  weight_decay: 5.e-4
  num_epochs: 40
  batch_size: 16
  test_epoch_interval: 5

hyperparam:
