---
data:
  type: CS
  train:
    data_roots:
      - /home/junsong_fan/diskf/data/cityscapes/leftImg8bit/train
      - /home/junsong_fan/diskf/data/cityscapes/leftImg8bit_scg_png/train
      - ./resources/labels/cityscapes/uniform_instance_pnt1.txt
    data_type: [Image, Superpixel, Point]
    image_size: [513, 1025]
    #image_size: [513, 513]
    #rand_short: [256, 768]
    rand_scale: [0.5, 1.5]
    rand_crop: true
    rand_mirror: true
    rand_point_shift: 0
    point_size: 3
    max_superpixel: 2048
    rtn_image_label: true
    post_resize_labels: [65, 129]
    #post_resize_labels: [65, 65]

  test:
    data_roots:
      - /home/junsong_fan/diskf/data/cityscapes/leftImg8bit/val
      - /home/junsong_fan/diskf/data/cityscapes/gtFine/val
    data_type: [Image, Image]
    image_size: ~
    image_suffix: [.png, _color.png]

model:
  type: ProjectionModel
  args:
    base: DeeplabV2_VGG16
    base_args:
      num_classes: 19
      pretrained: ./pretrained/vgg16_20M.pth
    base_stage_names: [c7]
    base_stage_dims: [1024]
    proj_mid_dims: 512
    proj_out_dims: 256
    normalize: false
  params_lr_mult:
    - ['fc8', 10]
  #- ['proj', 10]

optimizer:
  type: SGD
  args:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  #type: AdamW
  #args:
  #  lr: 0.0001
  scheduler:
    type: Poly
    args:
      num_epochs: 40
      power: 0.9
  batch_size: 16
  num_epochs: 40

test:
  test_epoch_interval: 10
  test_scales: [0.75, 1, 1.25]
  mirror: true

train_func: point_pmask_cl

hyperparam:
  threshold: 0.3
  warmup: 8

  proj_type: pix2img
  num_pos: 1
  expand_batch: true

  lambda_pmask: 1
  lambda_cl: 2

  use_memory: true
  capacity: 64

  focal: false
  focal_power: 2

  weighted_map: true
  use_weight_grad: false
  add_mean: false